# Generated by Django 3.2 on 2022-02-22 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Treatments',
            fields=[
                ('treatment', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('price', models.IntegerField()),
                ('duration', models.CharField(max_length=200)),
            ],
        ),
    ]
