# Generated by Django 3.2 on 2022-02-22 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0002_rename_treatments_treatment'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='description',
            field=models.TextField(default='', max_length=500),
        ),
    ]
