# Generated by Django 3.2 on 2022-02-22 17:46

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0003_treatment_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='treatment_image',
            field=cloudinary.models.CloudinaryField(default='static/default.jpeg', max_length=255, verbose_name='image'),
        ),
    ]
