# Generated by Django 3.2 on 2022-02-23 12:48

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0005_remove_treatment_treatment_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='treatment_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
