# Generated by Django 3.2 on 2022-03-17 21:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatments', models.CharField(choices=[('Orthodontics', 'Orthodontics'), ('Teeth Cleaning', 'Teeth Cleaning'), ('Gum Surgery', 'Gum Surgery'), ('Teeth Whitening', 'Teeth Whitening')], max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
